### ISSUE TITLE
Public API improvements

### ISSUE THREAD

**Issue by bezelga** [magnetis/spok#25]
Hi there!

By using Spok nowadays I need to "know" the internal module of it:

`Spok::Workday.workday?`

The public API could be simpler with something like `Spok.workday?`

This would be also good for future refactors of the internals, avoiding major breaking changes for the users.

Thoughts?

**Comment by luizParreira** [comment]
Hm, I agree. 👍 

It looks cleaner and avoids exposing internal module names.

**Comment by ruan-brandao** [comment]
That is a good idea. I think we can create a new branch to work on API improvements for version 1.1.x

**Comment by rrrcompagnoni** [comment]
It's available on v2.1.0.
