### ISSUE TITLE
Add new calendars

### ISSUE THREAD

**Issue by ruan-brandao** [magnetis/spok#28]
Currently, Spok has support for only two calendars: `:brasil` and `:bovespa`. In order to be useful to more people, more calendars can be added to the project.

To add a new calendar, the these steps can be followed:
1. Create a new file on [lib/spok/config/](https://github.com/magnetis/spok/tree/master/lib/spok/config) directory;
2. The file must be a `.yml` file named with the calendar name. Example: `united_states.yml`;
3. Add the holiday dates to the calendar. You can check the [existing calendar files](https://github.com/magnetis/spok/tree/master/lib/spok/config) for examples;
4. Note that there is no need to add weekend dates, only holidays;
5. Add the calendar name to the `Spok::Workday::CALENDARS` constant [here](https://github.com/magnetis/spok/blob/master/lib/spok/workday.rb#L12).

**Comment by janukan** [comment]
Hey I am interested in making a calendar for Canada, any limit on how far back or how forward it goes in years?

**Comment by ruan-brandao** [comment]
@janukan Thanks for your interest in contributing!
There is no limit on how far back or forward it must go, the more dates on it, the better.
The rule is that it must go at least one year in the future. And as a convention, we start the calendars on the year 1993.

**Comment by zainalmustofa** [comment]
Hi Iam interested, will working in the Indonesia Calendar

**Comment by hartly97** [comment]
I'll work on the Czech Republic calendar.

**Comment by Garbar** [comment]
Hi I am interested, will work in the Ukrainian Calendar

**Comment by gpks** [comment]
Hi, I can do Polish calendar :)

**Comment by wladimirgramacho** [comment]
I'll be doing German calendar :smile:

**Comment by vikasnautiyal** [comment]
Hi I am in interested to add an Indian calendar. But it is not very straight forward.
India is divided into 29 states and 7 union territories. The states have their own calendar, it can have not only national holidays but alsostate specific important dates could also be observed as holiday.
So these States and UTs can have different holidays. I am not sure how to go about, any inputs will be appreciated. Thanks.

**Comment by pille1842** [comment]
I just added a PR for Austrian holidays.

> India is divided into 29 states and 7 union territories. The states have their own calendar, it can not only have national holidays but also state specific important dates could also be observed as holiday.

@vikasnautiyal Austria (and I assume many other countries, including e.g. the US) has the same problem. Each of the states has its own public holidays. I have, for now, only added the federal holidays that are the same throughout the country.

**Comment by severinkaelin** [comment]
Hi, I'll work on a Swiss calendar.

**Comment by juliegoat** [comment]
I'll do the United States calendar tonight!

**Comment by kokkonisd** [comment]
I'm doing the France calendar right now!

**Comment by kokkonisd** [comment]
#61

**Comment by thefifthisa** [comment]
I'd love to do a calendar for the Philippines!

**Comment by n1ckbren** [comment]
I will do it for Ukraine

**Comment by severinkaelin** [comment]
Thanks for your interest @n1ckbren. But there is already a PR https://github.com/magnetis/spok/pull/45 from @Garbar.

**Comment by jsantos** [comment]
Just wondering how is every contributor handling dates for public holidays (e.g. Easter, Chinese New Year, Hari Raya Haji). 

Are you guys actually using some logic for this or simply repeating the same dates every year? The latter might cause some inconsistencies on the gem.

**Comment by severinkaelin** [comment]
@jsantos I think most people are using some kind of script to generate the dates. @isabel22 shared a script https://github.com/magnetis/spok/pull/48.

**Comment by konpyuta** [comment]
I'd like to work on the calendars for China and Hong Kong!

**Comment by owura82** [comment]
Hi, I'd like to add the calendar for Ghana.

**Comment by owura82** [comment]
Hi I'd like to add a calendar for Ghana

**Comment by rpontes** [comment]
After this merge: https://github.com/magnetis/spok/pull/81 will be not necessary to add calendars to the gem.
