### ISSUE TITLE
Spok Calendar specs are failing for Malaysia Calendar

### ISSUE THREAD

**Issue by lidimayra** [magnetis/spok#79]
To reproduce, run:

```
rspec spec/lib/spok/calendars_spec.rb
```

Following error is displayed:

```
Failures:
  1) Spok Calendars has valid dates for malaysia
     Failure/Error: expect(valid_calendar).to eq(true)
     
       expected: true
            got: false
     
       (compared using ==)
     # ./spec/lib/spok/calendars_spec.rb:13:in `block (3 levels) in <top (required)>'

Finished in 0.02115 seconds (files took 0.39914 seconds to load)
28 examples, 1 failure
```

This happens because [Malaysia yml file](https://github.com/magnetis/spok/blob/master/lib/spok/config/malaysia.yml) is the only one that stops at year 2019.

The spec checks if the last date contained in each country's configurations is at least one year ahead of the current date. Therefore, it fails for Malaysia, since this scenario is false.

To make this spec pass, it would be necessary to fill Malaysia config files with holidays corresponding to 2020 (at least).

**Comment by lucasmazza** [comment]
@ruan-brandao deleted the Malaysian calendar on 3ef86405ffdfa8c5691a5cd58ad9b22c9e221043, fixing the build. If anyone needs to use spok with an updated version of this calendar, I recommend waiting to use the API from #81 instead of bundling a new YAML to the repo.
